# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60cb1fd3ee26a3c90d8e6cb75d80f2b8dafac51b8e7e617fac7d7356061018d3e2b7267a0af3e3181d25705628b8cb672b806c0942f633ba2165cc9daee7ceef

test:
  secret_key_base: b9dd5d2c46344992681a9747c08b5088c7024a5b7cd1678ab33e4d0a212eca2b1aa51561ed89a719c8339faf9647d2d06b306a7e77ce91fdd02efe0697161038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
